import 'package:flutter/material.dart';
import 'package:flutterapp/madapp/generatedhome64widget/generated/GeneratedContentWidget1.dart';
import 'package:flutterapp/madapp/generatedhome64widget/generated/GeneratedNavbarWidget1.dart';
import 'package:flutterapp/madapp/generatedhome64widget/generated/GeneratedFooterWidget1.dart';

/* Frame HOME 6.4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHOME64Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1464.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 426.0,
                      height: 1464.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(234, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1389.0,
                              right: null,
                              bottom: null,
                              width: 427.0,
                              height: 75.0,
                              child: GeneratedFooterWidget1(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 136.0,
                              right: null,
                              bottom: null,
                              width: 347.0,
                              height: 920.0,
                              child: GeneratedContentWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -1.1368683772161603e-13,
                              right: null,
                              bottom: null,
                              width: 426.0,
                              height: 98.0,
                              child: GeneratedNavbarWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
