import 'package:flutter/material.dart';
import 'package:flutterapp/madapp/generatedhome66widget/generated/GeneratedFooterWidget3.dart';
import 'package:flutterapp/madapp/generatedhome66widget/generated/GeneratedContentWidget3.dart';
import 'package:flutterapp/madapp/generatedhome66widget/generated/GeneratedNavbarWidget3.dart';

/* Frame HOME 6.6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHOME66Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1464.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 426.0,
                      height: 1464.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(234, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1389.0,
                              right: null,
                              bottom: null,
                              width: 426.0,
                              height: 75.0,
                              child: GeneratedFooterWidget3(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 135.0,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 1197.0,
                              child: GeneratedContentWidget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 426.0,
                              height: 98.0,
                              child: GeneratedNavbarWidget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
