import 'package:flutter/material.dart';
import 'package:flutterapp/madapp/generatedhome63widget/generated/GeneratedNavbarWidget2.dart';
import 'package:flutterapp/madapp/generatedhome63widget/generated/GeneratedFooterWidget2.dart';
import 'package:flutterapp/madapp/generatedhome63widget/generated/GeneratedContentWidget2.dart';

/* Frame HOME 6.3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHOME63Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1464.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 426.0,
                      height: 1464.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(234, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1389.0,
                              right: null,
                              bottom: null,
                              width: 426.0,
                              height: 75.0,
                              child: GeneratedFooterWidget2(),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 141.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 1176.0,
                              child: GeneratedContentWidget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 426.0,
                              height: 98.0,
                              child: GeneratedNavbarWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
