import 'package:flutter/material.dart';
import 'package:flutterapp/madapp/generatedhome2widget/generated/GeneratedFooterWidget15.dart';
import 'package:flutterapp/madapp/generatedhome2widget/generated/GeneratedContentWidget15.dart';
import 'package:flutterapp/madapp/generatedhome2widget/generated/GeneratedNavbarWidget15.dart';

/* Frame HOME 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHOME2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 854.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 426.0,
                      height: 854.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(234, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 779.0,
                              right: null,
                              bottom: null,
                              width: 426.0,
                              height: 75.0,
                              child: GeneratedFooterWidget15(),
                            ),
                            Positioned(
                              left: 51.0,
                              top: 119.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 563.0,
                              child: GeneratedContentWidget15(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 426.0,
                              height: 98.0,
                              child: GeneratedNavbarWidget15(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
