import 'package:flutter/material.dart';
import 'package:flutterapp/madapp/generatedhome62widget/generated/GeneratedFooterWidget8.dart';
import 'package:flutterapp/madapp/generatedhome62widget/generated/GeneratedNavbarWidget8.dart';
import 'package:flutterapp/madapp/generatedhome62widget/generated/GeneratedContentWidget8.dart';

/* Frame HOME 6.2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHOME62Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 854.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 426.0,
                      height: 854.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(234, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 779.0,
                              right: null,
                              bottom: null,
                              width: 426.0,
                              height: 75.0,
                              child: GeneratedFooterWidget8(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 156.0,
                              right: null,
                              bottom: null,
                              width: 341.0,
                              height: 489.0,
                              child: GeneratedContentWidget8(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -1536.0,
                              right: null,
                              bottom: null,
                              width: 811.0,
                              height: 1634.0,
                              child: GeneratedNavbarWidget8(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
